# Use root/example as user/password credentials
version: '3.1'

services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 8081:8081
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
